### ISSUE TITLE
results.create fails if defect is not provided as boolean in req_data

### ISSUE THREAD

**Issue by flowrean-marcus** [qase-tms/qase-python#1]
if data (TestRunResultCreate) does not have defect as either True or False the request (results.create) fails with:
```
Got unexpected status code: 422 b'{"status":false,"errorMessage":"Data is invalid.","errorFields":[{"field":"defect","error":"The defect field must be true or false."}]}'
```

This also makes the qase-robotframework listener fail as it is expecting defect to be set to either True or False

**Comment by zeburek** [comment]
@flowrean-marcus thanks for report!
I will check

**Comment by zeburek** [comment]
@flowrean-marcus can you please check, the problem should be gone.

**Comment by flowrean-marcus** [comment]
@zeburek yes, the problem's gone, thank you for the fix!
