### ISSUE TITLE
The result is not sent if two browser windows are opened when running tests

### ISSUE THREAD

**Issue by augustvavreliy** [qase-tms/qase-python#106]
I have a problem with running tests in parallel. I use pytest-xdist for this. It opens several windows to run. So when you open several windows the result of the execution of cases is not sent.
![image](https://github.com/qase-tms/qase-python/assets/68571539/b71a3a97-b0a3-4342-80a3-ec07a646cd6c)
![image](https://github.com/qase-tms/qase-python/assets/68571539/fa81a8fb-1f7c-4ceb-a60f-3201944b44b0)

**Comment by n3r** [comment]
Hello @augustvavreliy 

Can you provide a little bit more information about libraries you use?

**Comment by augustvavreliy** [comment]
Shure 
qase-pytest == 5.0.1
pytest == 7.4.0
playwright == 1.35.0
pytest-playwright == 0.3.3
pytest-xdist == 3.3.1
pytest-dependency == 0.5.1
python == 3.11.1

**Comment by gibiw** [comment]
@augustvavreliy Hi! This problem should not be relevant in the latest versions of the reporter.
