### ISSUE TITLE
qase-to-complete-run argument does not make the run completed

### ISSUE THREAD

**Issue by danielPashht** [qase-tms/qase-python#107]
Free qase plan. When I specify qase-to-complete-run as well as other arguments, all of them do it's works except this one. Run remains in running state and needs to be completed manually. What extra info can I provide for you to debug this?

**Comment by n3r** [comment]
Hello @danielPashht 

What version of `qase-pytest` do you use?

**Comment by danielPashht** [comment]
hi, @n3r 4.2.0

**Comment by ayevtushik** [comment]
I have the same issue: qase-pytest 5.0.2: 

I've added --qase-testops-run-complete=true  to CLI command and to addopts in pytest.ini. Anyway runs are not completed

**Comment by avhb** [comment]
I am facing the exact same issue - paying enterprise customer

Tried the following cli arguments:
```
--qase-testops-run-complete=True
--qase-testops-run-complete=true

```
both don't work

Workaround by using the environment variable as such:
`QASE_TESTOPS_RUN_COMPLETE=True`

but that is not ideal in my workflow, would love to see this fixed

VERSIONS:
![image](https://github.com/qase-tms/qase-python/assets/66175168/23b58a46-6251-463e-aee3-7cc5e9da2f41)

**Comment by ry-sny** [comment]
I'm also seeing this issue
