### ISSUE TITLE
pytest: error: unrecognized arguments: --qase-testops-project=PRJCODE --qase-testops-plan-id=3

### ISSUE THREAD

**Issue by vadimkop** [qase-tms/qase-python#109]
When running in the pipeline, I encounter an error: pytest: error: unrecognized arguments: --qase-testops-project=PRJCODE --qase-testops-plan-id=3
Here's an example command: pytest -vs --base_url "prod" --app_version "ios" -m prod_mobile --qase-mode="testops" --qase-testops-api-token="<my token>" --qase-testops-project=PRJCODE --qase-testops-plan-id=3 --reruns=1 tests/

**Comment by n3r** [comment]
Hello @vadimkop!

I can confirm that problem exists. Preparing a fix for that.

**Comment by vadimkop** [comment]
> Hello @vadimkop!
> 
> I can confirm that problem exists. Preparing a fix for that.

Thanks)
