### ISSUE TITLE
Test result status in test run always In process after update the status to PASSED

### ISSUE THREAD

**Issue by benhe-crypto** [qase-tms/qase-python#11]
The test was break during the testing but not do any ending action(qase api to end the test)

Test result details page display all step pass and get the test result status is passed
![image](https://user-images.githubusercontent.com/82073911/153164798-40e66a8a-5e7c-4903-bc29-9ae6aed18f58.png)

TestRunResultInfo(hash='ad18416977acea13f4f4acd0a62954284ac7f490', comment='', stacktrace=None, run_id=258, case_id=1172, steps=None, status='Passed', is_api_result=False, time_spent=None, end_time='2022-02-09 09:02:37', attachments=[])

But it show in process in Test result page
![image](https://user-images.githubusercontent.com/82073911/153165046-36aa56f4-724c-44ce-b0f5-eca568c13b39.png)

**Comment by 1ivliev** [comment]
@benhe-crypto, greetings. Please tell us about your executable test data and your environment.
Thanks
