### ISSUE TITLE
pytest 4.2.0 async mode does not send results to test run report. Sync sends everything

### ISSUE THREAD

**Issue by alekseilantsov** [qase-tms/qase-python#112]
I had launched a test run by test plan:
`pytest tests/ --target_env=stage --qase-mode=testops --qase-to-plan=4 --qase-to-run-title=custom_to_plan -n 5`
started run 529
The test run was completed successfully
`Completing run 529
Run ID:529 was finished successfully` No qase related errors were present in the output.
But there are no results in the run report

I cloned this run in web interface and started another one by test run:
`pytest tests/ --target_env=stage --qase-mode=testops --qase-to-run=530 -n 5` and again, run completed, no errors, but the report is empty
'Completing run 530
Run ID:530 was finished successfully'

And another one in the next clone. Sync version this time:
`pytest tests/ --target_env=stage --qase-mode=testops --qase-to-run=531 -n 5 --qase-to-mode=sync`
This time every qase marked result is sent to qase.io and displayed in the report, even the ones that are not related to the initital test run.

![image](https://github.com/qase-tms/qase-python/assets/135048981/ca8bc455-b0bc-4a71-ad4b-156540824ce6)

qase-related packages:
`qase-pytest==4.2.0
qase-python-commons==1.0.4
qaseio==3.2.1`

I expect that both sync and async modes should send the results that are related to the test plans or runs, depending on the parameters.
I'm 100% sure that there ARE test cases that match the initial test plan as long as everything went well with the test plan on qase-pytest==2.3.2
qaseio==2.2.4

Please fix.
This is quite disappointing when there're so many compatibility issues in different versions. I considered switching to 5.0.0 but it requires rewriting all the parameters and options again, plus running with test plan option does not work at all.

**Comment by alekseilantsov** [comment]
UPD for 5.0.1: async works, but sends all the cases to the report if I run with --qase-testops-run-id option.
Is sync disabled in 5.x?

**Comment by gibiw** [comment]
@alekseilantsov Hi! This problem should not be relevant in the latest versions of the reporter.
