### ISSUE TITLE
Result is not sent to Qase with @qase.fields (pytest)

### ISSUE THREAD

**Issue by vadimkop** [qase-tms/qase-python#115]
<img width="623" alt="Screenshot 2023-06-16 at 15 54 21" src="https://github.com/qase-tms/qase-python/assets/60034374/24ed1603-0ba3-47a0-b79b-adc4b6e094b7">
<img width="1304" alt="Screenshot 2023-06-16 at 15 54 41" src="https://github.com/qase-tms/qase-python/assets/60034374/9cc4fc1f-36d2-40b0-bd76-95357d1ba80a">

If I add new decorations to my tests, I cannot see results in Qase after running pipeline
But if I don't use @qase.fields - it's ok, I see results in Qase

**Comment by n3r** [comment]
Issue is confirmed. We will fix that on the backend.

**Comment by oligazar** [comment]
@n3r Still not working with `qase-pytest-5.0.2`
