### ISSUE TITLE
Invalid type --qase-testops-plan-id

### ISSUE THREAD

**Issue by vadimkop** [qase-tms/qase-python#116]
If I use --qase-testops-plan-id=5 in CLI, I see qaseio.exceptions.ApiTypeError: Invalid type for variable 'id'. Required value type is int and passed type was str at ['id']

**Comment by alekseilantsov** [comment]
Try these changes locally https://github.com/qase-tms/qase-python/pull/114. IDK how much time it'll take for the maintainers to approve the PR.

**Comment by gibiw** [comment]
This problem has been resolved in the latest versions.
