### ISSUE TITLE
--qase-testops-bulk doesn't work with sync

### ISSUE THREAD

**Issue by vadimkop** [qase-tms/qase-python#117]
I used `--qase-testops-bulk=False` in the CLI, but I received the test results only after the pipeline was finished. I also tried 
```
--qase-testops-bulk="False"
--qase-testops-bulk="false"
--qase-testops-bulk=false
```

**Comment by gibiw** [comment]
In the latest versions of the reporter, bulk uploading is always used. You can change the batch size using the parameter "--qase-testops-batch-size"
