### ISSUE TITLE
Error using Qase listener

### ISSUE THREAD

**Issue by MakEurChoIcE** [qase-tms/qase-python#125]
I am trying to use the newer version of qase-robotframework but after making the adjustments comment in Issue #95, I'm facing a new error:

`[ ERROR ] Taking listener 'qaseio.robotframework.listener' into use failed: Listener 'qaseio.robotframework.listener' does not have mandatory 'ROBOT_LISTENER_API_VERSION' attribute.`

I'm currently using version 1.1.1 but we are having some issues with our integration and I was trying to see if in the newer version it's alredy fixed.

**Comment by christofer019** [comment]
I am currently trying to integare qase-robotframework, but the listener doesn't found after installed it

Error:
`[ ERROR ] Taking listener 'qaseio.robotframework.Listener' into use failed: Importing listener 'qaseio.robotframework.Listener' failed: ModuleNotFoundError: No module named 'qaseio.robotframework.listener'`

Screenshot:
<img width="1358" alt="Screen Shot 2023-09-05 at 14 48 29" src="https://github.com/qase-tms/qase-python/assets/49891968/1bb5b8ce-7600-4a85-be2b-878604ed0f8d">

the version used is:
qase-python-commons - 2.0.3
qase-robotframework    - 2.0.0
qaseio                              - 3.4.1
Python                             - 3.10.10

**Comment by MakEurChoIcE** [comment]
@christofer019 There is some problem with the 2.0 version with the folder name. The code are expecting the folder name starting with lower-case and not upper-case. 

You can bypass this problem following the "instructions" on #95 and changing the folder's name.

**Comment by christofer019** [comment]
thankyou sir, that's work. but now i got this error:

**Comment by MakEurChoIcE** [comment]
This issue should not be marked as completed since we are still having issues with it. Issue also related #94

**Comment by MakEurChoIcE** [comment]
> I have the same problem as @christofer019
> 
> `[ ERROR ] Calling method 'end_test' of listener 'qaseio.robotframework.QaseListener' failed: AttributeError: 'str' object has no attribute 'id'`
> 
> Has the problem been solved so far @MakEurChoIcE @christofer019 ?

@fabisento I didn't try updating QASE for some time. I will save some time this week to try that and post here my feedback.
