### ISSUE TITLE
Issue in the library qase-robotframework when using keywords in robotframework script

### ISSUE THREAD

**Issue by andrea77apple** [qase-tms/qase-python#144]
This is the example to describe the issue:

_Robot Script_

*** Settings ***
Documentation   An example test suite

*** Test Cases ***
Scenario without keyword
          Log To Console    OK

Scenario with keyword
          MyKeyword

*** Keywords ***
MyKeyword
          Log To Console    KO

when I execute the script with the command _robot --listener qaseio.robotframework.QaseListener .\test-dummy.robot_
this error occured:

**[ ERROR ] Calling method 'end_test' of listener 'qaseio.robotframework.QaseListener' failed: ApiTypeError: Invalid type for variable '0'. Required value type is dict and passed type was TestStepResultCreate at ['steps'][0]**

I suppose there are problems when keywords are used because in the first scenario (without keyword) there are not problems.

**Comment by gibiw** [comment]
@andrea77apple Hi! Try to use the latest version of reporter - 3.2.3
