### ISSUE TITLE
Passing description prop for newly created test runs

### ISSUE THREAD

**Issue by aleksandr-corrily** [qase-tms/qase-python#152]
**Problem:**
Currently, there is no way to pass a 'description' property for a new created test-run, only title.
For example, [playwright ](https://www.npmjs.com/package/playwright-qase-reporter) allows to pass that value via env variable.

**Proposal:**
Add a property --qase-testops-run-description for passing description for test tuns.

**Comment by gibiw** [comment]
@aleksandr-corrily thanks for noticing! We have published a new version of python reporters. Now you can pass the test ran description. You can find all options in this [documentation](https://github.com/qase-tms/qase-python/blob/main/qase-pytest/docs/CONFIGURATION.md#configuration-options)
