### ISSUE TITLE
Unrecognized arguments on v5.0.2

### ISSUE THREAD

**Issue by lisasinov8** [qase-tms/qase-python#153]
Current config:
<img width="1034" alt="image" src="https://github.com/qase-tms/qase-python/assets/122978676/d4f08fd5-bfab-4004-88f8-09935c559e57">

I'm running the following: 
pytest --qase-mode=testops --qase-testops-api-token=xxxx --qase-testops-project=RWAT --qase-testops-plan-id=1  
and getting the following error:

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --qase-testops-api-token=xxxx --qase-testops-project=RWAT --qase-testops-plan-id=1
  inifile: None
  rootdir: C:\Users\LisaduPlessis\Documents\GitHub\redrabbit-automation-tests

<img width="1253" alt="image" src="https://github.com/qase-tms/qase-python/assets/122978676/8d208a00-af04-4d90-b4b6-11b7e481e093">

**Comment by lisasinov8** [comment]
Hi guys, any luck with this?

**Comment by NickVolynkin** [comment]
@lisasinov8 Hi there!

I couldn't reproduce the “error: unrecognized arguments”. Maybe the issue is in version compatibility between pytest and qase-pytest. Could you please post the output of `pip show pytest`?

There's one error in the log which comes from pytest itself, not qase-pytest:

> inifile: None

To fix it, try creating a file `pytest.ini` in the same directory as `qase.config.ini`, and with the following content. Change paths to source and tests to what they are in your project.

```ini
[pytest]
pythonpath = src
testpaths = tests
python_files = tests.py test_*.py
```

**Comment by lisasinov8** [comment]
Thank you @NickVolynkin 

Output as requested:

![image](https://github.com/qase-tms/qase-python/assets/122978676/2cdefc03-eb7f-4713-a419-4fc81d961094)


I just want to confirm around this comment "To fix it, try creating a file pytest.ini in the same directory as qase.config.ini, and with the following content. Change paths to source and tests to what they are in your project."

Is this the configuration file you're referring to? And the correct directory?

![image](https://github.com/qase-tms/qase-python/assets/122978676/5d1bddb9-dd73-46c4-9d94-15b65e6bf7c8)

**Comment by NickVolynkin** [comment]
Oh, and I found a typo in my previous comment: `qase.config.ini` → `qase.config.json`. See an example of this files' contents in the readme: https://github.com/qase-tms/qase-python/tree/master/qase-pytest#example-qaseconfigjson

**Comment by lisasinov8** [comment]
@NickVolynkin I've tried the above but still not having any luck on the command line.
I created two files, pytest.ini and qase.config.json.  
They're both in my repo's root.

![image](https://github.com/qase-tms/qase-python/assets/122978676/7b2cecf9-2f06-4c75-b055-0e57a3ae4600)


Here's the info I put in the qase.config.json file

```
{
	"mode": "testops",
	"fallback": "report",
	"report": {
		"driver": "local",
		"connection": {
			"local": {
				"path": "./build/qase-report",
				"format": "json"
			}
		}
	},
	"testops": {
		"bulk": true,
		"api": {
			"token": "xxxxxxxxxxxxxxx",
			"host": "qase.io"
		},
		"run": {
            "id": 1,
			"title": "Test run title",
			"complete": true
		},
        "plan": {
            "id": 1
        },
		"defect": true,
		"project": "RWAT",
		"chunk": 200
	},
	"framework": {
		"pytest": {
			"capture": {
				"logs": true,
				"http": true
			}
		}
	},
	"environment": "local"
}
```
When I run the command, I get the following:

<img width="1257" alt="image" src="https://github.com/qase-tms/qase-python/assets/122978676/96c42075-4e1e-4a31-81d5-080280ce7d75">

**Comment by NickVolynkin** [comment]
@lisasinov8 it appears that your system can find the `pytest` executable, but then `pytest` can't find the package `qase-pytest`.

First of all, try running tests like this:

```bash
python -m pytest --qase-mode=testops ...
```

If it won't help, try creating a virtual environment in the same directory as your project with autotests, activate it, install `pytest` and `qase-pytest`, and try once more.

https://virtualenv.pypa.io/en/latest/installation.html#windows

**Comment by lisasinov8** [comment]
@NickVolynkin downgrading to qaseio==3.4.1 resolved the issue, so I suspect the bug is in the latest qasio version.

**Comment by NickVolynkin** [comment]
Hey @lisasinov8! We have released new versions recently, please try `qase-pytest==5.0.5`.

Here's the full list of latest versions:
```
qase-pytest==5.0.5
qase-python-commons==2.0.9
qaseio==4.0.1
```

**Comment by lisasinov8** [comment]
Got it working, thanks @NickVolynkin !
