### ISSUE TITLE
not send qase result during api_results.create_result_bulk.

### ISSUE THREAD

**Issue by Golom3402** [qase-tms/qase-python#156]
test_run is created, but the result of running a separate autotest is not sent.
qase-pytest version 5.0.2,  in run options i used: 
pytest -v tests/ --qase-mode=testops --qase-testops-api-token="***"  --qase-testops-project="***"  --qase-testops-run-title="***"  
 

in debug console we see the next result:

[Qase] Uploading attachments for Run ID: 1685...
[Qase] Sending results to test run 1685. Total results: 1. Results in a chunk: 200.
[Qase] Sending chunk #1. Chunk size: 1... 
[Qase] ⚠️  Error at sending results for run 1685 (Chunk #1): 2 validation errors for create_result_bulk
resultcreate_bulk
  Missing required argument [type=missing_argument, input_value=ArgsKwargs((<qaseio.api.r...e)], author_id=None)])}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.6/v/missing_argument
result_create_bulk
  Unexpected keyword argument [type=unexpected_keyword_argument, input_value=ResultcreateBulk(results=...one)], author_id=None)]), input_type=ResultcreateBulk]
    For further information visit https://errors.pydantic.dev/2.6/v/unexpected_keyword_argument

**Comment by n3r** [comment]
Hello @Golom3402!

Do you have `qase.config.json` in addition to the inline arguments?

**Comment by Golom3402** [comment]
I have a feeling that the reason is a compatibility issue with one of the supporting packages for qase-pytest 5.0.2

**Comment by ry-sny** [comment]
I am also seeing this issue when using the bulk option.
