### ISSUE TITLE
Automated runs are not automatically completed 

### ISSUE THREAD

**Issue by Anthony-Bou-Khalil** [qase-tms/qase-python#174]
I'm using the cli to run my script like this:
`pytest --qase-mode=testops --qase-testops-api-token=<API_TOKEN> --qase-testops-project=<PROJECT_CODE> script.py` 

The test run is successfully run and tests pass on the qase.io but my qase test run is not complete.
It should be marked as completed by default according to the documentation.
Adding `--qase-testops-run-complete=true` did not make a difference.

**Comment by NickVolynkin** [comment]
@Anthony-Bou-Khalil hello and thank you for reporting. We know about this issue and will resolve it in the next package update. For now, you can control this behavior in configuration file or with an environment variable

**Comment by Anthony-Bou-Khalil** [comment]
@NickVolynkin Thank you. Upgrading to `qase-pytest==5.0.5` has fixed my issue using CLI.
