### ISSUE TITLE
Set loglevel in qase-robotframework

### ISSUE THREAD

**Issue by flowrean-marcus** [qase-tms/qase-python#21]
Hello,

We're using the qase-robotframework listener to feed the test results into Qase but we're not utilising the mapping of step names in code compared to the step names in Qase. Now the listener library floods our logs with warning messages saying that no step was found for each keyword but I'd like to control the loglevel so I can keep our other logs in the project.
Currently as a workaround I'm setting the loglevel of the whole project to ERROR but this makes all our logs disappear, not just the Qase warnings.

**Comment by MakEurChoIcE** [comment]
Hello, just to inform, i opened the feature request.
https://roadmap.qase.io/feature-requests/p/set-log-level-for-qase-with-robot-framework

**Comment by zeeshanyshaikh** [comment]
Please check https://github.com/qase-tms/qase-python/pull/62

**Comment by MakEurChoIcE** [comment]
> Please check #62 if that can help

I think that will sure help us.
