### ISSUE TITLE
Conflicting imports in qaseio.__init__

### ISSUE THREAD

**Issue by DarkFlameBEN** [qase-tms/qase-python#212]
In qaseio.__init__ in build 4.0.2 there are 2 Configuration imports:
line 41: from qaseio.configuration import Configuration
line 65: from qaseio.models.configuration import Configuration

One should be renamed

**Comment by gibiw** [comment]
@DarkFlameBEN thanks for noticing! We’ve just fixed it in qase-api-client 1.0.1
