### ISSUE TITLE
InternalErrors

### ISSUE THREAD

**Issue by d2therak** [qase-tms/qase-python#226]
Adding Qase-Python to my local pytest tests causes a ton of InternalError messages. Removing package removes all errors. 

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/_pytest/main.py", line 285, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/_pytest/main.py", line 339, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/_pytest/logging.py", line 807, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/_pytest/main.py", line 364, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     teardown.throw(outcome._exception)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/_pytest/warnings.py", line 111, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     teardown.throw(outcome._exception)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/_pytest/assertion/__init__.py", line 176, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/pluggy/_callers.py", line 88, in _multicall
INTERNALERROR>     next(wrapper_gen)  # first yield
INTERNALERROR>     ^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/qase/pytest/plugin.py", line 101, in pytest_runtest_protocol
INTERNALERROR>     self.start_pytest_item(item)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/qase/pytest/plugin.py", line 162, in start_pytest_item
INTERNALERROR>     self._set_suite(item)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/qase/pytest/plugin.py", line 274, in _set_suite
INTERNALERROR>     self._get_suite(item)
INTERNALERROR>   File "/opt/homebrew/lib/python3.12/site-packages/qase/pytest/plugin.py", line 285, in _get_suite
INTERNALERROR>     title = file_path + '.' + module
INTERNALERROR>             ~~~~~~~~~~^~~~~
INTERNALERROR> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by NickVolynkin** [comment]
@d2therak what versions of qase packages do you have?

```sh
pip freeze | grep qase
```

**Comment by d2therak** [comment]
qase-api-client==1.0.1
qase-api-v2-client==1.0.0
qase-pytest==6.0.1
qase-python-commons==3.0.3

**Comment by gibiw** [comment]
@d2therak can you share information about how you run the tests and the full path to the directory with the tests?

**Comment by d2therak** [comment]
Hi there, I am running them via command line IE pytest test_3OutletsTest.py. The full path to directory of tests is /Users/derekrozycki/Desktop/python api automation/test_30OutletsTest.py

**Comment by gibiw** [comment]
@d2therak update the package to version 6.0.2

**Comment by d2therak** [comment]
Thank you, this appears to have fixed issue. Again thank you for fast turn around on this
