### ISSUE TITLE
Generate test case automatically for pytest

### ISSUE THREAD

**Issue by hex0cter** [qase-tms/qase-python#23]
Hi,

I noticed the `qaseio` library already has full support for test case creation/deletion. But it doesn't seem to be used in the `pytest` hooks, which means, for `pytest`, users still have to create the test case in Qase and link the testID in their code manually. Is there any plan to implement this feature for pytest anytime soon?

**Comment by 1ivliev** [comment]
Hello @hex0cter 
Yes, this feature is planned to be implemented soon.
We'll let you know when it's updated. I will close this appeal for now.
