### ISSUE TITLE
@qase.suite does not work

### ISSUE THREAD

**Issue by ry-sny** [qase-tms/qase-python#231]
```
@qase.suite("Example")
class TestExample:
    def test_1():
        assert True
    def test_2():
        assert False
```

Given the above example I would expect both tests to be added to the Example test suite. When I run the code they are not added to the suite.

I then tried adding @qase.suite ("Example") to each test but that still didn't work.

**Comment by gibiw** [comment]
@ry-sny  thanks for noticing! We’ve just fixed it in qase-pytest 6.0.3
