### ISSUE TITLE
Command line option for capturing logs (--qase-pytest-capture-logs) doesn't work 

### ISSUE THREAD

**Issue by AFerster** [qase-tms/qase-python#234]
We are currently using qase-pytest, version - 6.1.0b1

When we try to add this option to our GitHub action, we are getting error:
`pytest: error: unrecognized arguments: --qase-pytest-capture-logs=true`

Our full list of requirements for out project: 
pytest-xdist==3.5.0
pytest==8.0.0
allure-pytest==2.13.2
requests==2.32.0
dynaconf==3.2.4
Faker==22.0.0
dataclasses-json==0.6.3
qase-pytest==6.1.0b1
setuptools==70.3.0
flake8==7.0.0
pre-commit==3.6.1
lxml==5.2.1
pillow==10.3.0
peewee==3.17.3
pymysql==1.1.1
attrs==23.2.0
qase-python-commons==3.1.0b4
qase-api-client==1.0.2
qase-api-v2-client==1.0.0

**Comment by gibiw** [comment]
@AFerster  thanks for noticing! Try to update qase-pytest to 6.1.0b2.

**Comment by AFerster** [comment]
Thank you for a quick response but this option doesnt work still
We run this list of command line options:
```
pytest  -v 
 --qase-mode=testops
--qase-debug=true  
--qase-pytest-capture-logs=true  
--qase-testops-batch-size=50  
--qase-testops-project=AA    
--qase-testops-run-title=autotests-10214271609-manual-run-autotests  
--qase-testops-run-complete=true  tests -m qase_title
```

but logging is marked to be false: 

```
"framework": {
         "pytest": {
            "capture_logs": false
         }
```

**Comment by gibiw** [comment]
@AFerster Try to update qase-pytest to 6.1.0b3.
