### ISSUE TITLE
QASE not sending the latest result when using --reruns

### ISSUE THREAD

**Issue by rogitan** [qase-tms/qase-python#246]
Hi,

We have tried all possible solutions, but we still aren't receiving the latest test results in QASE after triggering a rerun but it does upload the screenshots and log.txt file

**Comment by gibiw** [comment]
@rogitan Thank you for contacting us.

Can you provide more information?
1. What version of the reporter are you using?
2. What command do you use to run the tests?

**Comment by rogitan** [comment]
hi @gibiw,

1. We are using version qase-pytest 5.0.6, additionally we are also using pytest-rerunfailures 12.0
2. and we are using command, pytest -v -m <markername> --reruns <number of retry>
we also tried using pytest -v -k <testname> --reruns <number of retry>



for item number 2, we are also generating html file and using --numprocesses for parallel execution
but even without those in the command, we still not getting the latest test result "STATUS"

But again the screenshot and log.txt files are uploaded in QASE, say if you have 3 rerun, it will upload all the log.txt file and screenshots for 3 reruns. But only the initial status i.e., "failed" will be the final status of the test regardless if test is PASSED in the second rerun.

**Comment by rogitan** [comment]
![image](https://github.com/user-attachments/assets/2046f50b-fa15-4c7d-b279-2410b79c7375)

**Comment by tspnn** [comment]
We are experiencing the same issue.
- xdist: 3.6.1
- qase-pytest: 6.1.0b1
- rerunfailures: 14.0

`pytest -s -n 2 --reruns 3`

Additionally, we have noticed that log files from the reruns contain logs from the previous runs, which is a bit confusing.

**Comment by gibiw** [comment]
@rogitan @tspnn Hi! We fixed this issue in version 6.1.1b1. Try it and come back with feedback. Thanks

**Comment by tspnn** [comment]
Hi @gibiw 

We've upgraded to the latest version, and it seems to work inconsistently.

- Case 1: Test failed, 1st rerun passed:
    Run status: Failed
    Test Case status: Failed + 1 (retries tab is empty)

- Case 2: Test failed, 1st rerun passed:
    Run status: Passed
    Test Case status: Failed + 1 (retries tab is empty)

- Case 3: Test failed, 1st rerun passed:
    Run status: Passed
    Test Case status: Passed + 1 (retries tab contains one failed attempt) - as expected

- Case 4: Test failed, 3rd rerun passed:
    Run status: Failed
    Test Case status: Failed + 2 (retries tab contains two failed attempts)

I ran the the same test more than 20 times - most of the times the result was "Failed" even when rerun was successful. These four cases are just a brief summary of the issues encountered.

**Comment by n3r** [comment]
Hello @tspnn!

Can you check your project settings, please?
1. Go to `Settings` -> `Test Run` -> `Automated testing section`
2. Go to `Update test cases` block.
3. Change `Update for statuses` selectbox from `Passed only` to `All statuses`.
4. Try to run tests again.

**Comment by tspnn** [comment]
Hi @n3r 

That worked, thanks!

**Comment by rogitan** [comment]
> @rogitan @tspnn Hi! We fixed this issue in version 6.1.1b1. Try it and come back with feedback. Thanks

Thank you! I will apply the update and let you know

**Comment by rogitan** [comment]
> Hi @gibiw
> 
> We've upgraded to the latest version, and it seems to work inconsistently.
> 
> * Case 1: Test failed, 1st rerun passed:
>   Run status: Failed
>   Test Case status: Failed + 1 (retries tab is empty)
> * Case 2: Test failed, 1st rerun passed:
>   Run status: Passed
>   Test Case status: Failed + 1 (retries tab is empty)
> * Case 3: Test failed, 1st rerun passed:
>   Run status: Passed
>   Test Case status: Passed + 1 (retries tab contains one failed attempt) - as expected
> * Case 4: Test failed, 3rd rerun passed:
>   Run status: Failed
>   Test Case status: Failed + 2 (retries tab contains two failed attempts)
> 
> I ran the the same test more than 20 times - most of the times the result was "Failed" even when rerun was successful. These four cases are just a brief summary of the issues encountered.

did you change the imports? 

from qaseio.pytest import qase
to
from qase.pytest import qase

because after we did update the import

qase.attach(file_path, "image/png") >> this method is returning [Errno 2] No Such file or directory: 'image/png'

we only update qase-pytest to the recommended

**Comment by gibiw** [comment]
@rogitan Hi! Yes, we have changed the imports. You can find an instruction how to update here: https://github.com/qase-tms/qase-python/blob/main/qase-pytest/docs/UPGRADE.md#from-5x-to-6x

Here how to use `qase.attach`: https://github.com/qase-tms/qase-python/blob/main/qase-pytest/src/qase/pytest/decorators.py#L190

**Comment by gibiw** [comment]
@tspnn @rogitan Hi! Is the problem resolved?

**Comment by tspnn** [comment]
@gibiw, hi. Everything works fine now. The issue was resolved.
