### ISSUE TITLE
Issue with adding suits for the test with @qase.fields(("suite", "Example")) decorator

### ISSUE THREAD

**Issue by AFerster** [qase-tms/qase-python#248]
I am using `qase-pytest==6.1.0b3.`

The automatic filling of the "suits" field doesn't work through the decorator `@qase.fields(("suite", "Example"))`. I tried adding existing suites and creating new ones, but neither option updated anything in the repository or the test run. 

Other fields like severity, priority and description are added correctly

All settings for adding and updating optional fields is test run settings were enabled in qase web application.

I tried to find the cause using the --qase-debug option, but there were no error messages. 

I have the same problem with adding the test author using `@qase.fields(("author", "Example"))`, but this field is much less critical.

**Comment by AFerster** [comment]
Hi, сould you please provide feedback on this report? I'm eagerly awaiting updates on this matter. Is it possible that you were planning to address this in the upcoming updates of the plugin?

**Comment by gibiw** [comment]
@AFerster Hi! This will be fixed in the next versions of the reporter.

**Comment by AFerster** [comment]
Thank you!

**Comment by gibiw** [comment]
@AFerster We fixed the problem with the suite in version `qase-pytest 6.1.1b3`. Specifying the test author via fields will be available in the next releases.

**Comment by gibiw** [comment]
@AFerster We fixed the problem with the author in version `qase-pytest 6.1.1`
