### ISSUE TITLE
Report crashes if using --video option for pytest-playwright in pytest.ini

### ISSUE THREAD

**Issue by Egzekk** [qase-tms/qase-python#279]
If we use `--video on` option or `--video retain-on-failure` in pytest.ini or pyproject.toml as pytest's `addopts` argument, the qase is not uploading the video correctly and is giving an error:

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/automation-tests-6OnjhVOy-py3.12/lib/python3.12/site-packages/qase/commons/reporters/testops.py", line 79, in _send_results_threaded
    self.client.send_results(self.project_code, self.run_id, results)
  File "/home/runner/.cache/pypoetry/virtualenvs/automation-tests-6OnjhVOy-py3.12/lib/python3.12/site-packages/qase/commons/client/api_v1_client.py", line 127, in send_results
    results_to_send = [self._prepare_result(project_code, result) for result in results]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/automation-tests-6OnjhVOy-py3.12/lib/python3.12/site-packages/qase/commons/client/api_v1_client.py", line 142, in _prepare_result
    attached.extend(self._upload_attachment(project_code, attachment))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/automation-tests-6OnjhVOy-py3.12/lib/python3.12/site-packages/qase/commons/client/api_v1_client.py", line 92, in _upload_attachment
    raise ReporterException(e)
qase.commons.exceptions.reporter.ReporterException: [Errno 2] No such file or directory: '/tmp/playwright-pytest-qrqm08jg/7d88b43d4faddafbcecb954bf38990.webm'
``` 
Even if we add another option: `--output=results/playwright` it still throws an error as above.

The above mentioned options are officialy supported by playwright for pytest: https://playwright.dev/python/docs/test-runners

Could you please take a look at that? It is a quite an important feature for us to have.

**Comment by gibiw** [comment]
@Egzekk Hi! 

Steps to solve the problem:
- update the `qase-pytest` to 6.1.3 version
- create a file`conftest.py` with this code:
 ```python
import pytest

# Configure Playwright to record video for all tests
@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "record_video_dir": "./videos",  # Directory where videos will be saved
        "record_video_size": {"width": 1280, "height": 720}  # Video resolution
    }
```
- add `--video on` or `--video retain-on-failure` parameter

**Comment by Egzekk** [comment]
The issue has been resolved. For those encountering this problem, I recommend passing `"record_video_dir"` as `browser_context_args["record_video_dir"]`. This approach preserves the original naming conventions after the test and creates a default folder structure for each test. If you specify any other path, it will not follow the same naming convention or folder structure, resulting in a file with a random string name.

**Comment by Egzekk** [comment]
After further testing, I've encountered an issue with the suggested configuration:

```python
@pytest.fixture(scope="function")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "record_video_dir": "results/playwright",  # Directory for saving videos
        "record_video_size": {"width": 1280, "height": 720},  # Video resolution
    }
```

It creates an additional video file with a random string name next to the original one but outside of any folders, as shown in the first screenshot below:
    
<img width="588" alt="image" src="https://github.com/user-attachments/assets/843533ed-c7a9-45ff-8db3-af846c18a75d">

Expected behavior:
<img width="559" alt="Screenshot 2024-09-27 at 21 12 53" src="https://github.com/user-attachments/assets/ae8709a6-86e4-4242-978f-ee8fdab050a5">

For many tests and many videos, that can be a bit of problematic for us, to have it duplicated. Could you check it and adjust?

**Comment by gibiw** [comment]
@Egzekk Can you share your `pytest.ini`?

**Comment by Egzekk** [comment]
I moved it to pyprocject.toml, there is a section: 
```
[tool.pytest.ini_options]
addopts = "--show-capture=stdout --tracing retain-on-failure --video retain-on-failure --output=results/playwright --md-report --html=./results/html_reports/automation-report.html --self-contained-html"
log_cli = "true"
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
```

**Comment by gibiw** [comment]
@Egzekk Hi! Update the reporter to 6.1.5 version.

We improved the handling of videos and traces for Playwright tests.
You don't need to create a `conftest.py` file anymore. The video and trace will be attached to the test result
automatically.
You can configure the video and trace recording using the following parameters:

- `--video on` - add a video to each test
- `--video retain-on-failure` - add a video to each filed test
- `--tracing on` - add a trace to each test
- `--tracing retain-on-failure` - add a trace to each filed test
- `--output` - the directory where the video and trace will be saved. By default, the video and trace will be saved in
  the `test-results` directory.

**Comment by Egzekk** [comment]
> @Egzekk Hi! Update the reporter to 6.1.5 version.
> 
> We improved the handling of videos and traces for Playwright tests. You don't need to create a `conftest.py` file anymore. The video and trace will be attached to the test result automatically. You can configure the video and trace recording using the following parameters:
> 
> * `--video on` - add a video to each test
> * `--video retain-on-failure` - add a video to each filed test
> * `--tracing on` - add a trace to each test
> * `--tracing retain-on-failure` - add a trace to each filed test
> * `--output` - the directory where the video and trace will be saved. By default, the video and trace will be saved in
>   the `test-results` directory.

Hi @gibiw,

Thank you for your effort in enhancing the project. While the recent improvements are beneficial, an issue persists when running tests within a class module. The file path differs from the expected one.

Here is the structure you are expecting:
```
results/playwright/tests-front-control-room-test-login-py-test-login-chromium/video.webm
```

However, when the test resides within a class, Playwright generates the path as:
```
results/playwright/tests-front-control-room-test-login-py-testlogin-test-login-chromium
```

Please note the absence of the `-` (hyphen) in the path. This discrepancy is causing the upload to fail.

When the test is not within a test class, it does not throw an error, however I cannot see the uploaded video in the run as an attachment. Should I add something more?

**Comment by gibiw** [comment]
@Egzekk try to update to 6.1.6 version

**Comment by Egzekk** [comment]
Now it works. Thanks a lot!
