### ISSUE TITLE
Test runs created with the robotframework-qase listener have incorrect time spent amounts

### ISSUE THREAD

**Issue by flowrean-marcus** [qase-tms/qase-python#3]
Time spent on tests is showing an incorrect amount in Qase when using the robotframework listener.
As an example, a test that took 4 minutes and 8 seconds shows up in Qase as 68:43:47.

Robot:
![image](https://user-images.githubusercontent.com/56772537/117474845-a4ff1f80-af5b-11eb-99a7-703a688f9380.png)
Qase:
![image](https://user-images.githubusercontent.com/56772537/117475019-dd066280-af5b-11eb-8f7b-9481789007c2.png)

**Comment by zeburek** [comment]
@flowrean-marcus please recheck it with version v1.1.0
