### ISSUE TITLE
Python Package Index (PyPI) GitHub URL references stale branch (master)

### ISSUE THREAD

**Issue by quadespresso** [qase-tms/qase-python#315]
My apologies if this isn't the right place for this issue.

Ref: <https://pypi.org/project/qase-pytest/>

As a user visiting the URL above and seeking the GitHub repo link here:

![image](https://github.com/user-attachments/assets/6665c6bd-5665-4620-80f7-d2ef04ae652d)

Clicking on `Repository` sends me here: <https://github.com/qase-tms/qase-python/tree/master/qase-pytest>

However, it appears that the current default branch for this repo is `main`. It looks like the change from `master` to `main` happened around this time: https://github.com/qase-tms/qase-python/pull/183#issuecomment-2107964033

For whoever has the ability to affect this change: I would like to suggest changing the `Repository` URL to this:

<https://github.com/qase-tms/qase-python>

**Comment by gibiw** [comment]
@quadespresso Hi! Thank you for reaching out. We have updated the repository links in the code. They will be updated on PyPI with the next release.

**Comment by quadespresso** [comment]
@gibiw ah very nice -- I don't know why I didn't consider checking the `pyproject.toml` files (or even searching this repo for the URL in question).
