### ISSUE TITLE
behave support request

### ISSUE THREAD

**Issue by HeeSeok-kim** [qase-tms/qase-python#39]
hello

I want to 'Testrun' a Text in Qase using Behave and update that. Can you create a library?

thank you

**Comment by 1ivliev** [comment]
Hi! You can check out our roadmap or create a feature request at:
https://roadmap.qase.io/

**Comment by 1ivliev** [comment]
https://qase.canny.io/admin/board/feature-requests/p/behave-support-qase-reporter
