### ISSUE TITLE
Python Client. The attachments uploaded during a result submission are not shown in the test run

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-python#43]
### STR:
- use client v2.2.4 or later
- report the results into a run using python client
- send attachments with a result
### AR:
- in the UI of a test run, attachments are not shown
- they send attachments using `Qase.attachments.upload(self.project_code, file_path)`
- request is successful
- but, in the run there is no attachment for a case that was submitted
### ER:
- attachments passed with result should be shown in the run UI

**Comment by n3r** [comment]
Problem was solved in `qaseio-v.3.1.0`
