### ISSUE TITLE
Run qase with pytest.mark.parametrize gives an error

### ISSUE THREAD

**Issue by berpress** [qase-tms/qase-python#47]
For example
Create Project, add test case with id = 1
Run this test
```
@qase.id(1)
@pytest.mark.parametrize('a, b, c', [
                            [1, 2, 3],
                            [1, 3, 4]
                            ])
def test_sum(a, b, c):
    assert a + b == c
```
with settings in ini file
```
qs_enabled=true
qs_api_token=xxxxx
qs_project_code=YOUR CODE
qs_new_run=true
```

Result
```
INTERNALERROR> qaseio.client.services.BadRequestException: Got error during response: b'{"status":false,"errorMessage":"Test run is not active"}'
```
This happens because the run test is already closed when parameterization is started 2. But I don't use the flag **qs_complete_run**, why did the testran close?

pytest 7.1.2
qase-pytest  2.3.2

**Comment by n3r** [comment]
Fixed with in https://github.com/qase-tms/qase-python/releases/tag/qase-pytest-4.1.0
