### ISSUE TITLE
Often get internal server error

### ISSUE THREAD

**Issue by azkiadevy** [qase-tms/qase-python#5]
### Description 
since we are using the `qase-python` for integration pytest to qase io, sometimes we got the internal server error as in the picture below. mostly this happens in Indonesia working hour and At the same time, we run 4 test runs.

![Screen Shot 2021-09-15 at 11 12 14](https://user-images.githubusercontent.com/53743464/134298729-4a2f5427-55dc-45d4-a937-16ac08cbe6e1.png)
![Screen Shot 2021-09-15 at 11 12 22](https://user-images.githubusercontent.com/53743464/134298751-b85da6fc-e2e7-4308-a504-fe6135c321ce.png)

### Details 
**Question: could you guys please check the error that we got? and why this is happening? 
and this issue comes from which side? (qase-tms or something)**

```
...
INTERNALERROR>     raise ConnectionError(err, request=request)
INTERNALERROR> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

Running Time: 12.30 PM (Indonesian time) GMT+7 
and, this issue happens a lot during Indonesian working hours (noon)
Run 4 `test runs` at the same time.

### Tools version
Device: Mac mini (Mac os) 
Jenkins: 2.289.3
qase-pytest: latest version 2.3.0

**Comment by 1ivliev** [comment]
@azkiadevy hi! Do you still have this error repeated?

**Comment by azkiadevy** [comment]
> @azkiadevy hi! Do you still have this error repeated?

yes, even today I still got this error too. this error is unpredictable, I don't know the issue behind that
