### ISSUE TITLE
Pytest results are not uploaded in real time

### ISSUE THREAD

**Issue by EugenSusurrus** [qase-tms/qase-python#50]
Citing from the documentation execution logic:

https://github.com/qase-tms/qase-python/tree/master/qase-pytest#execution-logic

**Execute tests and publish results in a runtime, not waiting all run to finish**

With the new OpenAPI qaseio client the results are not uploaded in real time.

At our company we rely on this functionality because we have long-running tests and we don't want to loose the entire test run results if we are not able to upload them in bulk for some reason.

We would like to be available to further upload results in real time. How can we overcome this besides sticking with the old non OpenAPI generated client?

Thanks!

**Comment by n3r** [comment]
Fixed in #64.

We have added an option `--qase-to-mode` that accepts one of the following values: `sync` or `async`. If you want to see the results in realtime, you can use `sync` mode. Reporter will submit results right after test execution.
