### ISSUE TITLE
Can't change test run's title and setup environment_id

### ISSUE THREAD

**Issue by Nickolasll** [qase-tms/qase-python#52]
It would be greate to have functional to change test run's title and setup environment_id "out of the box", for example in pytest.ini.

I can do this now by monkey patching `QasePytestPlugin.create_testrun` function

```
run_create=RunCreate(
    title=f"{name} {datetime.now()}",
    cases=cases,
    is_autotest=True,
    environment_id=environment_id
),
```

But this would work fine until package update.

**Comment by n3r** [comment]
Hello @Nickolasll!

We have release a new version: https://github.com/qase-tms/qase-python/releases/tag/qase-pytest-4.1.0

Now you can set test run title and environment thought env variables or pytest.ini.
