### ISSUE TITLE
Support auto creating test cases for all reporters

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-python#56]
Need to add the ability to create test cases when sending bulk method results (in the absence of binding to the test case ID in Qase TMS). Several scenarios need to be supported:
- a complete absence of ID in test files
- the full presence of ID in test files
- the presence of both tests without ID and with ID
Example implementation in JS and PHP reporters:
https://github.com/qase-tms/qase-javascript/blob/master/qase-jest/src/index.ts
https://github.com/qase-tms/qase-phpunit/blob/main/src/Reporter.php

**Comment by hex0cter** [comment]
We have been waiting for this in pytest for a long time!

**Comment by n3r** [comment]
Support was added in https://github.com/qase-tms/qase-python/releases/tag/qase-pytest-4.0.0 and https://github.com/qase-tms/qase-python/releases/tag/qase-robotframework-v2.0.0
