### ISSUE TITLE
Support environment id passing for all reporters

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-python#57]
Need to add the ability to pass a flag with the value `environment_id` when sending a bulk request.
Documentation:
https://developers.qase.io/reference/create-run
Example implementation in JS reporter:
https://github.com/qase-tms/qase-javascript/blob/master/qase-playwright/src/index.ts

**Comment by n3r** [comment]
Support was added in https://github.com/qase-tms/qase-python/releases/tag/qase-pytest-4.0.0 and https://github.com/qase-tms/qase-python/releases/tag/qase-robotframework-v2.0.0
