### ISSUE TITLE
[qase-robotframework] Make tags case insensitive

### ISSUE THREAD

**Issue by flowrean-marcus** [qase-tms/qase-python#6]
Hello,

We are using the qase-robotframework listener to feed test results of our runs into Qase and we're using certain formatting tools in our project which make all tags on test cases lowercase. Recently I've found out that this makes the test runs empty because no link is found between test cases in Qase and the lowercase tags.

Would it be possible to make these tags case insensitive when parsing them?

**Comment by 1ivliev** [comment]
@flowrean-marcus Hi! This is added in PR https://github.com/qase-tms/qase-python/pull/10. Have a nice day!
