### ISSUE TITLE
Problem with integration  of Pytest with Qase

### ISSUE THREAD

**Issue by Stoyan-Iv** [qase-tms/qase-python#61]
When run the test through terminal with: "pytest test_base_page.py   --qase --qase-api-token='_________________________________________' --qase-project=MWA --qase-testru
n=1 --qase-debug "

The terminal throw this output: ''Invalid type for variable 'id'. Required value type is int and passed type was str at ['id']"

![image](https://user-images.githubusercontent.com/68859484/188880738-13459513-c338-4c80-bbf5-79b1b9e0ab95.png)

**Comment by n3r** [comment]
Will be fixed in v4.0.0.
