### ISSUE TITLE
The results of checking test cases are not displayed in the created testrun

### ISSUE THREAD

**Issue by Minni-Pooh** [qase-tms/qase-python#71]
I start my automation test run using `--qase --qase-api-token=______________ --qase-project=EXAMPLE --qase-testplan=5`.
Then test run is created in QASE, but it's empty, does not have any included testcases. Also after successful completion all tests in PyCharm, test run in QASE still is empty. 
Earlier it's work ok

from qase-python

Thank you! 
![qase_a](https://user-images.githubusercontent.com/116801371/198596605-b05601c2-a830-43a2-be55-446e8ffff214.jpg)

**Comment by n3r** [comment]
Hello @Minni-Pooh!

May I ask you to provide a little bit more details? What is the version of `qase-pytest` you were trying to use?
