### ISSUE TITLE
Terminal command to set environment doesn't work

### ISSUE THREAD

**Issue by Shaimyst** [qase-tms/qase-python#79]
Environment: MacOS, terminal

Terminal commands are not working for declaring environments for test runs. 
Command shown in README: --qase-environment=QS_ENVIRONMENT
Commands tested: 
--qase-environment=staging
--qase-environment=Staging
--qase-environment=STAGING
--qase-environment=QS_STAGING

The following terminal command runs the tests, creates and completes a test run, but doesn't fill out the environment.
Full terminal command used:
python3 -m pytest \ 
--qase-mode=testops --qase-to-api-token=<token> \
--qase-to-project=FLOW --qase-environment=Staging  <folder>

[
![Screenshot 2022-11-18 at 10 02 19](https://user-images.githubusercontent.com/9996979/202663960-42f1382c-f8a6-4383-b79d-5653ebb3b1ad.png)
![Screenshot 2022-11-18 at 10 03 57](https://user-images.githubusercontent.com/9996979/202663963-77b00d83-bdd7-490b-9875-5a232634c225.png)
![Screenshot 2022-11-18 at 10 04 27](https://user-images.githubusercontent.com/9996979/202663967-1951cf57-9069-4e74-9320-dd9df6d8edb5.png)
](url)

**Comment by 1ivliev** [comment]
@Shaimyst Hi! Try to use the `id_env` of env.

Example:
`pytest --qase-mode=testops --qase-to-api-token=<api_key> --qase-to-project=<project_code> --qase-environment=<id_env> test_example.py`

**Comment by 1ivliev** [comment]
We can get the `id_env` from the URL when changing any environment or from an API request.
https://developers.qase.io/reference/get-environments

**Comment by n3r** [comment]
@Shaimyst hi!

Right now, we don't have a support for a string value for environments. As @1ivliev mentioned above, you have to provide numerical value of the environment.

We are going to rework this behaviour in the beginning of the next year.
