### ISSUE TITLE
Cant link a pytest parametrized test with  an existing test case in qase

### ISSUE THREAD

**Issue by HeykKerimov** [qase-tms/qase-python#86]
The test run is empty after execution. It works well with not a parametrized test. 

<img width="667" alt="Снимок экрана 2022-12-12 в 11 39 16" src="https://user-images.githubusercontent.com/120369005/206999706-7122a627-530b-4f33-a3da-e1116e406147.png">
<img width="508" alt="Снимок экрана 2022-12-12 в 11 40 01" src="https://user-images.githubusercontent.com/120369005/206999712-89e635df-c1da-41c6-b52d-08130185b5c6.png">

**Comment by n3r** [comment]
Hello @HeykKerimov!

I have a quick question - do you have "_Auto create test cases_" option enabled in Project Settings?

**Comment by HeykKerimov** [comment]
@n3r Hello! Yes, it is enabled
<img width="695" alt="Снимок экрана 2022-12-14 в 12 47 07" src="https://user-images.githubusercontent.com/120369005/207562274-14aa0b20-65f9-4668-8071-70b84cb70a85.png">

**Comment by HeykKerimov** [comment]
@n3r Could you reproduce the issue?
pytest==7.1.2
qase-pytest==4.1.0

**Comment by n3r** [comment]
Hello @MatthewAlmeida 

In `qase-pytest:v5.x` we have added a new option: report mode. It saves report data to the disk. May I ask you to execute these tests and send zipped report folder to support@qase.io. That will help us to figure out what is going on.
