### ISSUE TITLE
Remove validation for number of params ResultCreate()

### ISSUE THREAD

**Issue by Tech-Goddess** [qase-tms/qase-python#87]
Hi,

Currently there's a limitation in qaseio that prevents us from creating a test result with more than 1 param.

See the validations dict in in qaseio/model/result_create.py:84

```
validations = {
        ('time',): {
            'inclusive_maximum': 31536000,
            'inclusive_minimum': 0,
        },
        ('time_ms',): {
            'inclusive_maximum': 31536000000,
            'inclusive_minimum': 0,
        },
        ('param',): {
            'max_items': 1,
            'max_properties': 1,
        },
    }
```

Seems like the API supports passing as many parameters as I want in the param dict of the test result object, but the sdk throws an error if the dict length is larger than 1. I tried commenting out the '('param',)' key of the dict and everything works fine, can this limitation be removed?

**Comment by n3r** [comment]
Hello @Tech-Goddess. This issue should have been fixed in release 3.1.1.

What version do you use?
