### ISSUE TITLE
Created three run ids but only wrote result comments on the latest one

### ISSUE THREAD

**Issue by miniduck123** [qase-tms/qase-python#93]
I tried to run the test on multiple platforms at the same time with Browserstack.

I noticed qase-pytest will create multiple run ids successfully but only
write the results in the latest one.
The screenshot is an example of the result:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/82485876/213339094-f504e9d5-f106-4921-8860-9b52853515eb.png">

May I separate the results into different run ids?

**Comment by n3r** [comment]
Hello @miniduck123!

May I ask you to provide a little bit more information about your configuration and lib versions?
